### ISSUE TITLE
Generator is always overwriting

### ISSUE THREAD

**Issue by Steven-N-Hart** [meanjs/generator-meanjs#139] opened 2015-10-29 03:01 UTC
I can not use the yeoman generator at all.  It always just wants to create a new repo.  What am I doing wrong?
```
git clone https://github.com/meanjs/mean.git meanjs
cd meanjs
git checkout v0.3.3
npm install

#Just to make sure I have the correct meanjs generator
npm install -g generator-meanjs 

yo meanjs:crud-module example
undefined
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? (Use arrow keys)
  master 
❯ 0.4.0 
  0.4.1 
node -v
v0.12.7

npm -v
2.14.4

yo --version
1.4.8

```

**Comment by codydaig** [comment] 2015-10-29 03:43
@Steven-N-Hart Duplicate of #119

**Closed by codydaig** 2015-10-29 03:43 UTC
